#!/bin/bash
# Author: Alfredo Hernández <aldomann@gmail.com>
echo "Select the PPAs you want to add"
echo "1) Basic PPAs         [6]"
echo "2) Exclusive PPAs     [2]"
echo "3) Extra repositories [8]"
echo "4) Delete duplicated  [*]"
read CHOICE

case $CHOICE in
	1)
		sudo add-apt-repository ppa:cybolic/vineyard-testing && sudo add-apt-repository ppa:gnome3-team/gnome3 && sudo add-apt-repository ppa:gnome3-team/gnome3-staging && sudo add-apt-repository ppa:tiheum/equinox && sudo add-apt-repository ppa:ubuntu-wine && sudo add-apt-repository ppa:webupd8team/java
		;;
	2)
		sudo add-apt-repository ppa:nuvola-player-builders/unstable && sudo add-apt-repository ppa:webupd8team/sublime-text-3
		;;
	3)
		echo 'deb http://linux.dropbox.com/ubuntu quantal main #Dropbox'>>'extras.list'
		echo 'deb http://archive.getdeb.net/ubuntu quantal-getdeb apps #Getdeb Apps'>>'extras.list'
		echo 'deb http://archive.getdeb.net/ubuntu quantal-getdeb games #Getdeb Games'>>'extras.list'
		echo 'deb http://dl.google.com/linux/chrome/deb/ stable main #Google Chrome'>>'extras.list'
		echo 'deb http://dl.google.com/linux/earth/deb/ stable main #Google Earth'>>'extras.list'
		echo 'deb http://dl.google.com/linux/musicmanager/deb/ stable main #Google Music Manager'>>'extras.list'
		echo 'deb http://dl.google.com/linux/talkplugin/deb/ stable main #Google Talk Plug-in'>>'extras.list'
		echo 'deb http://repository.spotify.com stable non-free #Spotify'>>'extras.list'
		chmod 644 'extras.list'
		sudo chown root:root 'extras.list'
		sudo mv 'extras.list' '/etc/apt/sources.list.d/extras.list'
		sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5044912E 46D7E7CF 7FAC5991 94558F59
		;;
	4)
		cd /etc/apt/sources.list.d/
		sudo rm -rf *.save
		sudo rm -rf *dropbox*.list *google*.list
		;;
	*)
		echo "Choose a valid option"
		exit 1
		;;
	# Eventuals [5]
		# ppa:gnome3-team/staging
		# ppa:nilarimogard/webupd8
		# ppa:otto-kesselgulasch/gimp
		# ppa:tombeckmann
		# ppa:videolan/master-daily

	# Not updated yet [2]
		# ppa:mohanr2222/circle
		# ppa:w-vollprecht
esac
