#!/bin/bash
# Author: Alfredo Hernández <aldomann@gmail.com>
echo "Select the applications you want to install"
echo "0) Uninstall [4]"
echo "1) Basics    [39] "
echo "2) Games     [3]"
echo "3) Exclusive [15]"
echo "4) Science   [1]"
echo "5) Testing   [2]"
read CHOICE

case $CHOICE in
	0) 
		sudo aptitude purge firefox firefox-locale-en firefox-locale-es xul-ext-ubufox
		notify-send "Uninstallation was successful"
		;;
	1) 
		sudo aptitude install alacarte bleachbit fonts-droid fonts-lmodern fonts-roboto gbrainy gdebi gimp gnome-cards-data google-chrome-unstable google-talkplugin gstreamer1.0-plugins-ugly icedtea-7-plugin inkscape libreoffice-l10n-es nautilus-image-converter oracle-java7-installer p7zip pdftk quadrapassel rar skype sound-juicer synaptic vineyard vlc wine aspell-ca aspell-en aspell-es hyphen-ca hyphen-en-us myspell-ca myspell-en-gb mythes-ca mythes-en-us wbritish wcatalan wspanish
		notify-send "Installation was successful"
		;;
	2) 
		sudo aptitude install gameconqueror vbam-gtk zsnes
		notify-send "Installation was successful"
		;;
	3) 
		sudo aptitude install bzr comix dropbox gcolor2 git gnac google-musicmanager-beta gparted gtk-3-examples moka-icon-theme moka-icon-theme-extras moka-icon-theme-symbolic ppa-purge sublime-text-installer thunar
		notify-send "Installation was successful"
		;;
	4)
		sudo aptitude install gelemental
		notify-send "Installation was successful"
		;;
	5)
		sudo aptitude install cutemupen mupen64plus
		notify-send "Installation was successful"
		;;
	*) 
		echo "Choose a valid option"
		exit 1
		;;
	# Not in use [25]
		# adobe-flashplugin arista cantor chromium-browser easytag faience-icon-theme faience-theme gnome-break-timer google-earth-stable gtk-vector-screenshot gwoffice hardinfo hedgewars menulibre minitube miro musique nuvolaplayer screenkey screenruler sparkleshare tucan unetbootin unoconv wesnot
	# Quarantine [9]
		# arista circle gnac gnome-clocks google-earth-stable hardinfo pitivi uberwriter pdfjam
esac
