#!/bin/bash
# Authors:
#	Alfredo Hernández <aldomann.designs@gmail.com>
#
# Description:
#	A script to manage config files (both system-wide and locally)
#
# Legal Stuff:
#	This script is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, version 3.

#	This script is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with this script. If not, see <http://www.gnu.org/licenses/>.

tabs 2
clear

echo "#--------------------------------------------#"
echo "#            Config Files Script             #"
echo "#--------------------------------------------#"

#----- FUNCTIONS -----#
function config-general {
	show_info 'What would you like to do?'
	echo
	echo "1) Change pacman.conf?      (system)"
	echo "2) Change journald.conf?    (system)"
	echo "3) Create .makepkg.conf?    (local)"
	echo "4) Set up Qt5 integration?  (system)"
	echo
	echo "8) Symlink zshrc and zsh_history?"
	echo "9) Symlink bashrc and bash_profile?"
	echo
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Change pacman.conf
	1)
		show_info 'Changing /etc/pacman.conf...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo sed -i 's@#CacheDir.*@CacheDir    = /tmp@g' /etc/pacman.conf
			if [ -d /var/cache/pacman ]; then
				sudo rm -rf /var/cache/pacman
			fi
			sudo sed -i 's@#Color@Color@g' /etc/pacman.conf
			sudo sed -i ':a;N;$!ba;s@#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist@\[multilib\]\nInclude = /etc/pacman.d/mirrorlist@g' /etc/pacman.conf
			clear && config-general
			;;
		# Negative action
		[Nn]* )
			clear && config-general
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-general
			;;
		esac
		;;
	# Change journald.conf in /etc/systemd/
	2)
		show_info 'Changing /etc/systemd/journald.conf...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo journalctl --vacuum-time=2d
			sudo sed -i 's@.*SystemMaxFileSize.*@SystemMaxFileSize=8M@g' /etc/systemd/journald.conf
			sudo sed -i 's@.*RuntimeMaxFileSize.*@RuntimeMaxFileSize=8M@g' /etc/systemd/journald.conf
			sudo sed -i 's@.*SystemMaxUse.*@SystemMaxUse=64M@g' /etc/systemd/journald.conf
			sudo sed -i 's@.*RuntimeMaxUse.*@RuntimeMaxUse=64M@g' /etc/systemd/journald.conf
			clear && config-general
			;;
		# Negative action
		[Nn]* )
			clear && config-general
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-general
			;;
		esac
		;;
	# Create makepkg.conf
	3)
		show_info 'Creating ~/.makepkg.conf...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			touch ~/.makepkg.conf
			echo "PKGEXT='.pkg.tar.xz'" > ~/.makepkg.conf
			clear && config-general
			;;
		# Negative action
		[Nn]* )
			clear && config-general
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-general
			;;
		esac
		;;
	# Set up Qt5 integration
	4)
		show_info 'Seting up Qt5 integration...'
		show_info 'This will install qt5ct qt5-styleplugins and edit /etc/environment'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -S qt5ct qt5-styleplugins --needed
			if ! grep -q "QT_QPA_PLATFORMTHEME=qt5ct" "/etc/environment"; then
				sudo bash -c "echo "QT_QPA_PLATFORMTHEME=qt5ct" >> /etc/environment"
			fi
			# TODO: modify qt5ct.conf
			clear && config-general
			;;
		# Negative action
		[Nn]* )
			clear && config-general
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-general
			;;
		esac
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && config-general;;
	esac
}
# ----------------------------------------------------------------------
function config-apps {
	show_info 'What would you like to do?'
	echo
	echo "1) Create .Rprofile? (local)"
	echo "2) Sublime Text?"
	echo "3) MPV?"
	echo "4) Tilix?"
	echo
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Create .Rprofile
	1)
		show_info 'Creating ~/.Rprofile...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			touch ~/.Rprofile
			echo '.libPaths("~/.R/x86_64-pc-linux-gnu-library/3.4")' > ~/.Rprofile
			clear && config-apps
			;;
		# Negative action
		[Nn]* )
			clear && config-apps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-apps
			;;
		esac
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && config-apps;;
	esac
}
# ----------------------------------------------------------------------
function config-games {
	show_info 'What would you like to do?'
	echo
	echo "1) Retroarch?"
	echo "2) EmulationStation?"
	echo "3) Warcraft III?"
	echo "4) StarCraft?"
	echo
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Set up Systemd Journald configuration
	1)
		show_info 'Doing something...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			echo "asd"
			clear && config-games
			;;
		# Negative action
		[Nn]* )
			clear && config-games
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.' && config-games
			;;
		esac
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && config-games;;
	esac
}
# ----------------------------------------------------------------------

#----- MESSAGE FUNCTIONS -----#
show_info() {
	echo -e "\033[1;34m$@\033[0m"
}
show_success() {
	echo -e "\033[1;32m$@\033[0m"
}
show_error() {
	echo -e "\033[1;31m$@\033[m" 1>&2
}

#----- MAIN FUNCTION -----#
function main {
	show_info 'What would you like to do?'
	echo
	echo "1) Change general config files?"
	echo "2) Change apps config files?"
	echo "3) Change games config files?"
	echo
	echo "e) Exit?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
		1) clear && config-general;; # General
		2) clear && config-apps;;    # Apps
		3) clear && config-games;;   # Games
		[Ee]* ) exit 99;;            # Quit
		[Qq]* ) exit 99;;            # Quit
		* ) clear && show_error 'Not an option, try again.' && main;;
	esac
}

#----- RUN MAIN FUNCTION -----#
main

# END OF SCRIPT
