#!/bin/bash
# Authors:
#	Sam Hewitt <hewittsamuel@gmail.com> (original script)
#	Alfredo Hernández <aldomann.designs@gmail.com>
#
# Description:
#	A post-installation bash script for Antergos
#
# Legal Stuff:
#	This script is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, version 3.

#	This script is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with this script.  If not, see <http://www.gnu.org/licenses/>.

# TODO:
	# @applications add AUR packages
	# @advanced change app-folder categories to universal ones w/ localisation
	# @cleanup update 2) leftover config files to Arch Linux syntax

	# @advanced nautilus scripts in en and es
	# @advanced nautilus the gtk python library is outdated in Arch

tabs 2
clear

echo '#--------------------------------------------#'
echo '#        Antergos Post-Install Script        #'
echo '#--------------------------------------------#'

#----- FUNCTIONS -----#
function sysupgrade {
	# Perform system upgrade
	echo
	show_info 'Performing system upgrade...'
	if [ -a /var/lib/pacman/db.lck ]; then
		sudo rm /var/lib/pacman/db.lck
	fi
	yaourt -Syua --noconfirm
	show_success 'Done.'
	notify-send "System upgrade was successful" -i system-software-update
	exit
}
# --------------------------------------------------
function applications {
	show_info 'What would you like to do?'
	echo
	echo "0) Set up Pacman configuration?"
	echo
	echo "1) Install basic apps?        [31]"
	echo "2) Install exclusive apps?    [18]"
	echo "3) Install games?             [4]"
	echo "4) Install GDM?"
	echo
	echo "5) Uninstall unused apps?     [8]"
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Enable extra repositories
	0)
		show_info 'Enabling extra repositories...'
		echo
		echo 'Repositories to be enabled: infinality-bundle'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Set up pacman.conf
				wget https://dl.dropboxusercontent.com/u/1564319/pacman.conf
				sudo mv pacman.conf /etc/pacman.conf
			# Add infinality-bundle key
				# sudo cp
				# sudo dirmngr
				# sudo pacman-key -r 962DDE58
				# sudo pacman-key -f 962DDE58
				# sudo pacman-key --lsign-key 962DDE58
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Install basic apps
	1)
		show_info 'Installing basic apps...'
		echo
		echo 'Current package list: adobe-source-han-sans-otc-fonts aisleriot bleachbit gbrainy gimp gnome-clocks gnome-mahjongg gnome-mines icedtea-web infinality-bundle inkscape jre7-openjdk lib32-gtk2 p7zip quadrapassel simple-scan skype sound-juicer wine wine-mono wine_gecko winetricks aspell-ca aspell-en aspell-es hunspell-en hunspell-es hyphen-en hyphen-es mythes-en mythes-es'
		# [Not in Arch repos]: hyphen-ca myspell-ca mythes-ca
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -S adobe-source-han-sans-otc-fonts aisleriot bleachbit gbrainy gimp gnome-clocks gnome-mahjongg gnome-mines icedtea-web infinality-bundle inkscape jre7-openjdk lib32-gtk2 p7zip quadrapassel simple-scan skype sound-juicer wine wine-mono wine_gecko winetricks aspell-ca aspell-en aspell-es hunspell-en hunspell-es hyphen-en hyphen-es mythes-en mythes-es
			notify-send "Installation was successful"
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Install extra apps
	2)
		show_info 'Installing exclusive apps...'
		echo
		echo 'Current package list: android-tools dconf-editor dropbox epiphany fluidsynth gaupol git gnome-boxes gnome-characters mcomix polari qtiplot sigil soundfont-fluid sparkleshare texlive-most thunar youtube-dl'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -S android-tools dconf-editor dropbox epiphany fluidsynth gaupol git gnome-boxes gnome-characters mcomix polari qtiplot sigil soundfont-fluid sparkleshare texlive-most thunar youtube-dl
			notify-send "Installation was successful"
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Install games
	3)
		show_info 'Installing games...'
		echo
		echo 'Current package list: steam vbam-gtk zsnes'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -S steam vbam-gtk zsnes
			notify-send "Installation was successful"
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Install GDM
	4)
		show_info 'Installing games...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -S gdm
			sudo systemctl disable lightdm.service
			sudo systemctl enable gdm.service
			sudo pacman -Rscn lightdm
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Uninstall apps
	5)
		show_info 'Uninstalling unused apps...'
		echo
		echo 'Current package list: brasero empathy gnome-shell-extension-dash-to-dock gnome-sound-recorder numix-frost-themes numix-icon-theme numix-icon-theme-square pidgin'
		# EXCLUSIVE: grbainy soud-juicer
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo pacman -Rscn brasero empathy gnome-shell-extension-dash-to-dock gnome-sound-recorder numix-frost-themes numix-icon-theme numix-icon-theme-square pidgin
			notify-send "Uninstallation was successful"
			clear && applications
			;;
		# Negative action
		[Nn]* )
			clear && applications
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			applications
			;;
		esac
		;;
	# Not in use [22]
		# alacarte arista atom cantor cutemupen easytag gameconqueror gnac gnome-clocks google-earth-stable google-musicmanager-beta hardinfo libreoffice-l10n-es menulibre minitube miro mupen64plus nuvolaplayer pitivi screenkey screenruler unetbootin
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && applications;;
	esac
}
# --------------------------------------------------
function fixapps {
	show_info 'What would you like to do?'
	echo
	# echo "0) Install Broadcom Wireless firmware (DELL)?"
	# echo "0) Enable media keys and GNOME interface for VLC"
	echo "1) Use symbolic icons in Inkscape?"
	echo "2) Enable smooth fonts in Wine?"
	echo "3) Crack Sublime Text 3 License?"
	echo "4) Set up Nautilus layout?"
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Install Broadcom Wireless
	0)
		show_info 'Installing Broadcom Wireless firmware...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			sudo aptitude install b43-fwcutter firmware-b43-installer
			sudo rfkill unblock all
			# type into terminal: 'cat /etc/modprobe.d/* | grep bcm' and see if the term 'blacklist bcm43xx' is there; if it is, type 'sudo gedit /etc/modprobe.d/blacklist.conf' and put a # in front of the line: 'blacklist bcm43xx'
			notify-send "Broadcom Wireless firmware installed successfully" -i network-wireless
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# VLC fixes
	0)
		show_info 'Applying fixes for VLC...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# VLC Media Keys
				vlcrc="$HOME/.config/vlc/vlcrc"
				sed -i 's/#global-key-play-pause=/global-key-play-pause=Media Play Pause/' $vlcrc
				sed -i 's/#global-key-next=/global-key-next=Media Next Track/' $vlcrc
				sed -i 's/#global-key-prev=/global-key-prev=Media Prev Track/' $vlcrc
				sed -i 's/#global-key-stop=/global-key-stop=Media Stop/' $vlcrc
			# VLC GNOME Interface
				cd $HOME/.config/vlc/
				rm -rf vlc-qt-interface.conf
				echo '[General]'>>'vlc-qt-interface.conf'
				echo 'IsFirstRun=0'>>'vlc-qt-interface.conf'
				echo 'geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1\x8a\0\0\x1:\0\0\x3r\0\0\x1t\0\0\x1\x8a\0\0\x1:\0\0\x3r\0\0\x1t\0\0\0\0\0\0)'>>'vlc-qt-interface.conf'
				echo>>'vlc-qt-interface.conf'
				echo '[MainWindow]'>>'vlc-qt-interface.conf'
				echo 'pl-dock-status=true'>>'vlc-qt-interface.conf'
				echo 'status-bar-visible=false'>>'vlc-qt-interface.conf'
				echo 'playlist-visible=false'>>'vlc-qt-interface.conf'
				echo 'adv-controls=0'>>'vlc-qt-interface.conf'
				echo 'bgSize=@Size(489 0)'>>'vlc-qt-interface.conf'
				echo 'playlistSize=@Size(-1 -1)'>>'vlc-qt-interface.conf'
				echo 'MainToolbar1="64;39-5;64;38-5;65;"'>>'vlc-qt-interface.conf'
				echo 'MainToolbar2="3-5;0-7;4-5;37-5;64-4;10-5;7-5;33;34-4;64-4;19-5;20-5;64-4;36-4;"'>>'vlc-qt-interface.conf'
				echo 'AdvToolbar="12-5;11-5;13-5;14-5;"'>>'vlc-qt-interface.conf'
				echo 'FSCtoolbar="64-4;3-5;0-7;4-5;37-5;64;25-5;8-1;33-1;34;64-1;36-4;64-4;"'>>'vlc-qt-interface.conf'
				echo 'InputToolbar='>>'vlc-qt-interface.conf'
				echo 'ToolbarPos=0'>>'vlc-qt-interface.conf'
				echo>>'vlc-qt-interface.conf'
				echo '[ToolbarProfiles]'>>'vlc-qt-interface.conf'
				echo '1\ProfileName=VLC 2.x.x Style'>>'vlc-qt-interface.conf'
				echo '1\Value="0|64;39;64;38;65;|0-2;64;3;1;4;64;7;9;64;10;20;19;64-4;37;65;35-4;|12;11;13;14;|43;33-4;44;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"'>>'vlc-qt-interface.conf'
				echo '2\ProfileName=VLC 1.1.x Style'>>'vlc-qt-interface.conf'
				echo '2\Value="0|64;39;64;38;65;|0-2;64;3;1;4;64;7;10;9;64-4;20;19;64-4;37;65;35-4;|12;11;13;14;|5-1;33;6-1;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"'>>'vlc-qt-interface.conf'
				echo '3\ProfileName=VLC 0.8.x Style'>>'vlc-qt-interface.conf'
				echo '3\Value="1|64;39-1;64;38;|2-1;32-4;0-5;1-5;32-5;3-5;5-5;6-5;4-5;32-5;10-1;64-1;35-1;65;|12-1;11-1;13-1;14-1;|33;37-4;|0-5;1-5;32-1;1-5;5-1;6-1;4-5;32-1;12-5;11-1;65;34-4;35-1;"'>>'vlc-qt-interface.conf'
				echo '4\ProfileName=Minimalist Style'>>'vlc-qt-interface.conf'
				echo '4\Value="0|64;65;|0-7;64;3-1;1-5;4-1;64;12-5;64-5;37-5;38-5;64-4;10-1;65;36-4;|11-5;13-5;14-5;|5-1;33;6-1;|0-5;64;3-5;1-5;4-5;64;12-5;65;34-4;35-1;"'>>'vlc-qt-interface.conf'
				echo '5\ProfileName=One-Liner Style'>>'vlc-qt-interface.conf'
				echo '5\Value="0|64;38;65;|0-4;64;3;1;4;64;7;10;9;64-4;39;64-4;37;65;36-4;|12;11;14;13;|5-1;33;6-1;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"'>>'vlc-qt-interface.conf'
				echo '6\ProfileName=Simplest Style'>>'vlc-qt-interface.conf'
				echo '6\Value="0||36-4;65-4;0-7;4-5;1-5;65-4;7-5;|12-4;11;13;||36-4;65-4;0-5;4-5;1-5;65;8-5;"'>>'vlc-qt-interface.conf'
				echo '7\ProfileName=GNOME'>>'vlc-qt-interface.conf'
				echo '7\Value="0|64;39-5;64;38-5;65;|3-5;0-7;4-5;37-5;64-4;10-5;7-5;33;34-4;64-4;19-5;20-5;64-4;36-4;|12-5;11-5;13-5;14-5;||64-4;3-5;0-7;4-5;37-5;64;25-5;8-1;33-1;34;64-1;36-4;64-4;"'>>'vlc-qt-interface.conf'
				echo 'size=7'>>'vlc-qt-interface.conf'
				echo>>'vlc-qt-interface.conf'
				echo '[FullScreen]'>>'vlc-qt-interface.conf'
				echo 'pos=@Point(0 0)'>>'vlc-qt-interface.conf'
				echo 'screen=@Rect(0 0 0 0)'>>'vlc-qt-interface.conf'
				echo 'wide=false'>>'vlc-qt-interface.conf'
			cd $HOME
			notify-send "VLC media player" "Desktop integration applied successfully" -i vlc
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# Inkscape icons
	1)
		show_info 'Applying fix for Inkscape...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Backup icons-old.svg
				sudo mv '/usr/share/inkscape/icons/icons-old.svg' '/usr/share/inkscape/icons/icons.svg'
				sudo mv '/usr/share/inkscape/icons/icons.svg' '/usr/share/inkscape/icons/icons-old.svg'
				# sudo cp '/usr/share/inkscape/icons/tango_icons.svg' '/usr/share/inkscape/icons/icons.svg'
			# Download new icons
				wget https://raw.github.com/gnome-design-team/gnome-icons/master/inkscape-symbolic/inkscape-icons.svg
				sudo mv inkscape-icons.svg '/usr/share/inkscape/icons/icons.svg'
			notify-send "Inkscape" "Symbolic icons have been installed successfully" -i inkscape
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# Wine fonts
	2)
		show_info 'Applying fix for Wine...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Source: http://files.polosatus.ru/winefontssmoothing_en.sh
			WINE=${WINE:-wine}
			WINEPREFIX=${WINEPREFIX:-$HOME/.wine}
			DIALOG=whiptail
			if [ ! -x "`which "$WINE"`" ]; then
				echo "Wine was not found. Is it really installed? ($WINE)"
				exit 1
			fi
			if [ ! -x "`which "$DIALOG"`" ]; then
				DIALOG=dialog
			fi
			TMPFILE=`mktemp` || exit 1
			$DIALOG --menu \
				"Please select font smoothing mode for wine programs:" 13 51\
				4\
					1 "Smoothing disabled"\
					2 "Grayscale smoothing"\
					3 "Subpixel smoothing (ClearType) RGB"\
					4 "Subpixel smoothing (ClearType) BGR" 2> $TMPFILE
			STATUS=$?
			ANSWER=`cat $TMPFILE`
			if [ $STATUS != 0 ]; then
				rm -f $TMPFILE
				exit 1
			fi
			MODE=0 # 0 = disabled; 2 = enabled
			TYPE=0 # 1 = regular;  2 = subpixel
			ORIENTATION=1 # 0 = BGR; 1 = RGB
			case $ANSWER in
				1) # disable
					;;
				2) # enable
					MODE=2
					TYPE=1
					;;
				3) # enable cleartype rgb
					MODE=2
					TYPE=2
					;;
				4) # enable cleartype bgr
					MODE=2
					TYPE=2
					ORIENTATION=0
					;;
				*)
					rm -f $TMPFILE
					echo Unexpected option: $ANSWER
					exit 1
					;;
			esac
			echo "REGEDIT4
			[HKEY_CURRENT_USER\Control Panel\Desktop]
			\"FontSmoothing\"=\"$MODE\"
			\"FontSmoothingOrientation\"=dword:0000000$ORIENTATION
			\"FontSmoothingType\"=dword:0000000$TYPE
			\"FontSmoothingGamma\"=dword:00000578" > $TMPFILE
			echo -n "Updating configuration..."
			$WINE regedit $TMPFILE 2> /dev/null
			rm -f $TMPFILE

			notify-send "Wine" "Font rendering has been fixed successfully" -i wine
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# Sublime Text Crack
	3)
		show_info 'Cracking Sublime Text license...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Source: https://gist.github.com/vertexclique/9839383
			# Source 2 (3083): http://appnee.com/sublime-text-3-universal-license-keys-collection-for-win-mac-linux/
			# wget http://dl.dropbox.com/u/1564319/sublime_text_linux_x32_build_3059
			# sudo mv sublime_text_linux_x32_build_3059 '/opt/sublime_text/sublime_text'
			wget http://dl.dropbox.com/u/1564319/sublime_text_linux_x64_build_3065
			sudo mv sublime_text_linux_x64_build_3065 '/opt/sublime_text/sublime_text'
			sudo chmod 755 '/opt/sublime_text/sublime_text'
			notify-send "Sublime Text" "The license has been installed successfully" -i sublime-text
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# Nautilus layout
	4)
		show_info 'Changing dconf files...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Regular nautilus
				dconf write /org/gnome/nautilus/icon-view/captions "['size', 'none', 'date_modified']"
				dconf write /org/gnome/nautilus/icon-view/thumbnail-size "96"
				dconf write /org/gnome/nautilus/preferences/executable-text-activation "'ask'"
				dconf write /org/gnome/nautilus/preferences/sort-directories-first "true"
				# dconf write /org/gnome/nautilus/window-state/geometry "'1195x675+380+200'"
				dconf write /org/gnome/nautilus/window-state/sidebar-width "'160'"
				nautilus -q
			# Root nautilus
				sudo dconf write /org/gnome/nautilus/icon-view/captions "['size', 'none', 'date_modified']"
				sudo dconf write /org/gnome/nautilus/icon-view/thumbnail-size "96"
				sudo dconf write /org/gnome/nautilus/preferences/executable-text-activation "'ask'"
				sudo dconf write /org/gnome/nautilus/preferences/sort-directories-first "true"
				# sudo dconf write /org/gnome/nautilus/window-state/geometry "'1195x675+380+200'"
				sudo dconf write /org/gnome/nautilus/window-state/sidebar-width "'160'"
			clear && fixapps
			;;
		# Negative action
		[Nn]* )
			clear && fixapps
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			fixapps
			;;
		esac
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && fixapps;;
	esac
}
# --------------------------------------------------
function advanced {
	show_info 'What would you like to do?'
	echo
	echo "1) Add 'Binaries' to PATH?"
	echo "2) Add Nautilus scripts?"
	echo "3) Add extra and hidden .desktop files?"
	echo "4) Set Moka/Adwaita/Roboto UI?"
	echo "5) Set Stock GNOME UI?"
	echo "6) Set up GNOME Shell app folders?"
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Binaries to PATH
	1)
		show_info 'Adding Binaries to PATH...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			echo 'export PATH="$HOME/Dropbox/Binaries:$PATH"'>>'.bash_profile'
			wget https://dl.dropboxusercontent.com/u/1564319/bashrc
			mv bashrc $HOME/.bashrc
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# Nautilus scripts
	2)
		show_info 'Adding scripts...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			cd /tmp
			wget http://dl.dropbox.com/u/1564319/nautilus-scripts.tar.gz
			tar -xzf nautilus-scripts.tar.gz
			rsync -a nautilus-scripts/ $HOME/.local/share/nautilus/scripts/
			nautilus -q
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# Desktop files
	3)
		show_info 'Adding hidden desktop files...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			# Extra Desktops
				cd /tmp
				wget http://dl.dropbox.com/u/1564319/changed-apps.tar.gz
				tar -xzf changed-apps.tar.gz
				cd changed-apps
				cp -r *.desktop $HOME/.local/share/applications
			# Hidden Desktops
				cd /tmp
				wget http://dl.dropbox.com/u/1564319/hidden-apps.tar.gz
				tar -xzf hidden-apps.tar.gz
				cd hidden-apps
				cp -r *.desktop $HOME/.local/share/applications
			gtk-update-icon-cache
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# Moka/Adwaita UI
	4)
		show_info 'Changing dconf files...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			dconf write /org/gnome/shell/overrides/button-layout "':close'"
			dconf write /org/gnome/desktop/wm/preferences/button-layout "':close'"
			dconf write /org/gnome/desktop/interface/font-name "'Roboto 11'"
			dconf write /org/gnome/desktop/interface/monospace-font-name "'Menlo 11'"
			dconf write /org/gnome/desktop/wm/preferences/titlebar-font "'Roboto Bold 11'"
			dconf write /org/gnome/desktop/interface/gtk-theme "'Adwaita'"
			# dconf write /org/gnome/desktop/wm/preferences/theme "'Adwaita'"
			dconf write /org/gnome/desktop/interface/icon-theme "'Moka'"
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# Stock GNOME UI
	5)
		show_info 'Changing dconf files...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			dconf write /org/gnome/shell/overrides/button-layout "':close'"
			dconf write /org/gnome/desktop/wm/preferences/button-layout "':close'"
			dconf write /org/gnome/desktop/interface/font-name "'Cantarell 11'"
			dconf write /org/gnome/desktop/wm/preferences/titlebar-font "'Cantarell Bold 11'"
			dconf write /org/gnome/desktop/interface/gtk-theme "'Adwaita'"
			# dconf write /org/gnome/desktop/wm/preferences/theme "'Adwaita'"
			dconf write /org/gnome/desktop/interface/icon-theme "'gnome'"
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# GNOME Shell app folders
	6)
		show_info 'Changing dconf files...'
		echo
		show_info 'Proceed? (Y)es, (N)o :' && read REPLY
		case $REPLY in
		# Positive action
		[Yy]* )
			gsettings set org.gnome.desktop.app-folders folder-children "['Games', 'Office', 'Utilities']"
			show_info 'In which language is your system? (E)nglish or (S)panish: ' && read REPLY
			case $REPLY in
			# English
			[Ee]* )
				games_appfolder="Games"
				utilities_appfolder="Utilities"
				office_appfolder="Office"
				;;
			# Spanish
			[Ss]* )
				games_appfolder="Juegos"
				utilities_appfolder="Utilidades"
				office_appfolder="Ofimática"
				;;
			esac # TODO: Note that there's no "* )" show_error option
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ name "$games_appfolder"
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ name "$utilities_appfolder"
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Office/ name "$office_appfolder"
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ apps "['battlenet.desktop.desktop', 'cutemupen.desktop', 'dolphin-emu.desktop', 'GameConqueror.desktop', 'gbrainy.desktop', 'gvbam.desktop', 'hedgewars.desktop', 'minecraft.desktop', 'Portal 2 (Beta).desktop', 'steam.desktop', 'war3roc.desktop', 'war3tft.desktop', 'five-or-more.desktop', 'four-in-a-row.desktop', 'gnome-chess.desktop', 'gnome-klotski.desktop', 'gnome-mahjongg.desktop', 'gnome-mines.desktop', 'gnome-nibbles.desktop', 'gnome-robots.desktop', 'gnome-sudoku.desktop', 'gnome-tetravex.desktop', 'hitori.desktop', 'iagno.desktop', 'lightsoff.desktop', 'quadrapassel.desktop', 'sol.desktop', 'starcraft.desktop', 'wesnoth-1.10.desktop', 'Worms Reloaded.desktop', 'zsnes.desktop', 'swell-foop.desktop', 'tali.desktop', 'wiican.desktop']"
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ apps "['bleachbit-root.desktop', 'bleachbit.desktop', 'ca.desrt.dconf-editor.desktop', 'dconf-editor.desktop', 'file-roller.desktop', 'gdebi.desktop', 'gnome-boxes.desktop', 'gnome-disks.desktop', 'gnome-system-log.desktop', 'gnome-tweak-tool.desktop', 'gparted.desktop', 'imagewriter.desktop', 'nexulockr.desktop', 'org.gnome.Boxes.desktop', 'org.gnome.FileRoller.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Logs.desktop', 'org.gnome.MultiWriter.desktop', 'pamac-manager.desktop', 'pamac-updater.desktop', 'seahorse.desktop', 'software-properties-drivers.desktop', 'software-properties-gnome.desktop', 'synaptic.desktop', 'system76-driver.desktop', 'usb-creator-gtk.desktop', 'vineyard-preferences.desktop', 'wine-uninstaller.desktop', 'wine-winecfg.desktop', 'winetricks.desktop']"
			gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Office/ apps "['bijiben.desktop', 'chrome-aohghmighlieiainnegkcijnfilokake-Default.desktop', 'chrome-ejjicmeblgpmajnghnpcppodonldlgfn-Default.desktop', 'chrome-felcaaldnbdncclmgdcncolpebgiejap-Default.desktop', 'chrome-hmjkmjkepdijhoojdojkdfohbdgmmhki-Default.desktop', 'chrome-ojcflmmmcfpacggndoaaflkmcoblhnbh-Default.desktop', 'dropbox.desktop', 'evince.desktop', 'evolution-calendar.desktop', 'evolution.desktop', 'libreoffice-base.desktop', 'libreoffice-calc.desktop', 'libreoffice-draw.desktop', 'libreoffice-impress.desktop', 'libreoffice-math.desktop', 'libreoffice-startcenter.desktop', 'libreoffice-writer.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Documents.desktop', 'pdfchain.desktop', 'sparkleshare.desktop']"
			clear && advanced
			;;
		# Negative action
		[Nn]* )
			clear && advanced
			;;
		# Error
		* )
			clear && show_error 'Sorry, try again.'
			advanced
			;;
		esac
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && hardware;;
	esac
}
# --------------------------------------------------
function hardware {
	show_info 'What would you like to do?'
	echo
	echo "1) Show disk usage?"
	echo "2) Show kernel version?"
	echo "3) Show system controllers?"
	echo "4) Show CPU, RAM and architecture information?"
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Show disk usage
	1)
		df -h
		hardware
		;;
	# Show kernel version
	2)
		uname -r # uname -a shows kernel and arch info
		hardware
		;;
	# Show system information
	3)
		lspci -v
		hardware
		;;
	# Show CPU, RAM, arch information
	4)
		grep "model name" /proc/cpuinfo && grep MemTotal /proc/meminfo && lscpu
		hardware
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && hardware;;
	esac
	}
# --------------------------------------------------
function cleanup {
	show_info 'What would you like to do?'
	echo
	echo "1) Remove orphaned packages?"
	echo "2) Clean package cache?"
	echo "3) Optimise pacman database?"
	echo "4) List locally installed packages?"
	echo "r) Return?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
	# Remove orphaned packages
	1)
		if [[ ! -n $(pacman -Qdtt) ]]; then
			show_success 'No orphans to remove.'
		else
			show_info 'Removing orphaned packages...'
			sudo pacman -Rns $(pacman -Qdtq)
			show_success 'Done.'
		fi
		echo
		cleanup
		;;
	# Clean package cache
	2)
		show_info 'Cleaning package cache...'
		sudo pacman -Sc --noconfirm
		show_success 'Done.'
		echo
		cleanup
		;;
	# Optimise pacman database
	3)
		show_info 'Optimising pacman database...'
		sudo pacman-optimize
		show_success 'Done.'
		echo
		cleanup
		;;
	# List locally installed packages
	4)
		show_info 'Listing packages...'
		sudo pacman -Qm
		show_success 'Done.'
		echo
		cleanup
		;;
	# Return
	[Rr]*)
		clear && main;;
	# Invalid choice
	* )
		clear && show_error 'Not an option, try again.' && cleanup;;
	esac
}
# --------------------------------------------------

#----- MESSAGE FUNCTIONS -----#
show_info() {
	echo -e "\033[1;34m$@\033[0m"
}
show_success() {
	echo -e "\033[1;32m$@\033[0m"
}
show_error() {
	echo -e "\033[1;31m$@\033[m" 1>&2
}

#----- MAIN FUNCTION -----#
function main {
	show_info 'What would you like to do?'
	echo
	echo "1) Perform system update and upgrade?"
	echo "2) Install favourite applications?"
	echo "3) Fix apps behaviour and appearance?"
	echo "4) Perform advanced configurations?"
	echo "5) View hardware information?"
	echo "6) Cleanup the system?"
	echo "q) Quit?"
	echo
	show_info 'Enter your choice:' && read REPLY
	case $REPLY in
		1) sysupgrade;;            # System Upgrade
		2) clear && applications;; # Install apps
		3) clear && fixapps;;      # Fix apps
		4) clear && advanced;;     # Advanced config
		5) clear && hardware;;     # Hardware info
		6) clear && cleanup;;      # System cleanup
		gsr) clear && nohup gnome-shell --replace & ;; # gnome-shell --replace
		[Qq]* ) exit 99;; # Quit
		* ) clear && show_error 'Not an option, try again.' && main;;
	esac
}

#----- RUN MAIN FUNCTION -----#
main

# END OF SCRIPT
